name: 自动推送到docker hub
on: push
jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 登录docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          folder: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 构建并推送到Docker hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: eggtoopain/react-app:latest
